codereport/jsource

jsrc/ar.c, jsrc/dtoa.c, jsrc/j.h, jsrc/js.h, jsrc/jtype.h, jsrc/k.c, jsrc/sl.c, jsrc/va2.c, jsrc/vcompsc.c, jsrc/ve.c, jsrc/vg.c, jsrc/vg.h, jsrc/vgranking.c, jsrc/vgsort.c, jsrc/vi.c, jsrc/viix.c, jsrc/vu.c, jsrc/x15.c, jsrc/xb.c
This resolves a part of https://github.com/codereport/jsource/issues/13
=> Removing C_LE  (Big Endian support)

.gitignore
This is just a minor pull request. For those that use clion this keeps the build directories and settings out of the repo.
=> remove clion's build and settings via .gitignore

jsrc/CMakeLists.txt
Removed `.h` files from target sources.
Added `target_include_directories(j PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})` to tell it where the header files are.
This gives us a few less lines of code to maintain.
Formatting happened so some lines have been shifted
=> Remove .h files from target sources in CMakeLists.txt. Replaced with target_include_directories.

jsrc/f2.c, jsrc/io.c, jsrc/j.h, jsrc/jdlllic.c, jsrc/js.h, jsrc/jtype.h, jsrc/m.h, jsrc/x15.c, jsrc/xa.c, jsrc/xd.c, jsrc/xf.c, jsrc/xh.c, jsrc/xl.c, jsrc/xo.c, jsrc/xt.c
- Removes macros for Power PC.
- Both mac and linux are unix, so `SYS & UNIX` is always true, so some stuff could be removed.
- `SY_MAC` and `SY_LINUX` were not used.
- `SYS_LILENDIAN` and `SYS_ANSI` are not defined, so they are interpreted as 0. Some stuff could be removed.
We probably want someone with a mac to build and test this aswell since I can't test the mac macros locally.
`SYS_LINUX` and `SYS_MACOSX` remain. They seem to be used in a more functional way and require more thought to remove.
=> Removing even more SYS stuff

README.md
I saw godbolt supported python. Though it doesn't run the script. So I added the link. I was wanting to add C#.  Though  Godbolt doesn't support C# yet. There is an open issue from 2018.
=> Add c# example to readme and godbolt for python.

CMakeLists.txt, jsrc/adverbs/ao.c, jsrc/dtoa.c, jsrc/j.h, jsrc/k.c, jsrc/m.c, jsrc/parsing/p.c, jsrc/verbs/vg.c, jsrc/verbs/vgsort.c, jsrc/verbs/vgsortq.h, jsrc/verbs/vsb.c
This removes misc macros (most of them unused) and ARM NEON include.
`-Wunused-macros` was useful in finding unused macros. I added it to the warnings in the CMakeLists.txt, but not as an error. It seems to give some false positives, likely because it only checks the current build configuration.
=> Misc removals

CMakeLists.txt
adding this exception for the werror lets me compile again on gcc10
i think this resolves https://github.com/codereport/jsource/issues/126 ?
=> Fix compiling in GCC 8+ -Wno-cast-function-type

jsrc/fnmatch.h, jsrc/io.c, jsrc/j.h, jsrc/jconsole.c, jsrc/jt.h, jsrc/xenos/x.c, jsrc/xenos/x15.c, jsrc/xenos/xd.c, jsrc/xenos/xf.c, jsrc/xenos/xl.c
This removes or reduces the scope of some non-portable headers. They were either unused or easy to replace.
I will create an issue for the rest of the non-portable headers I found.
=> Remove some non-portable headers

jsrc/jconsole.c, jsrc/verbs/vfrom.c
I had couple of errors building this on mac, this should fix those. I'm not 100% sure if the locale change is equivalent to the previous, but at least locally the tests passed.
- `newlocale`, `uselocale` and `locale_t` were defined in `xlocale.h`
- replaced with `setlocale(LC_NUMERIC, "C")`
- `jsrc/verbs/vfrom.c` used `i` uninitialised in some cases
- set `i = 0` in those cases, as the loops would have done previously
- also removed unused assignments and variables
=> Fix build for mac

jsrc/verbs/vasm.h
This one is never defined, which means we can simplify this code.
=> Remove compiler conditional on OVF

docs/.gitignore, docs/CMakeLists.txt, docs/scripts/preprocessor.py, docs/source/verbs.rst
tldr; We can now use markdown table syntax in RST file. Command for building docs is same as before (i.e. ``cmake -G \"Ninja Multi-Config\" -B build -DDOCS:STRING=YES && ninja -C build -f build-Release.ninja``). This was achieved by modifying cmake docs command from `` ${SPHINX_EXECUTABLE} -b html`` to ``${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/preprocessor.py --input ${SPHINX_SOURCE} --output ${SPHINX_SOURCE}/__output__ && ${SPHINX_EXECUTABLE} -b html``. Preprocessor may be useful for other custom RST syntax in future. Additional RST parsing can be added to ``docs/scripts/preprocessor.py`` in future.
Resolves https://github.com/codereport/jsource/issues/120.
Now, we can write tables in RST file using markdown syntax. This is pretty much as simple as it can get re. writing …
=> write markdown tables in RST file

jsrc/verbs/dyadic/take_drop.cpp
There is no mention of `b` in the related statement, but it does introduce `c`. It looks very much like like a copy-paste of a few lines above, where the update of the variable name has been forgotten.
=> Use correct variable name in TODO message

jsrc/verbs/vrand.c
Thank you compiler for pointing that out ;)
```
[68/131] Building C object jsrc/CMakeFiles/j.dir/Debug/verbs/vrand.c.o
../jsrc/verbs/vrand.c:49: warning: macro "two_to_the_31" is not used [-Wunused-macros]
49 | #define two_to_the_31 (0x80000000L)
```
=> Remove unused macro two_to_the_31

jsrc/io.c, jsrc/m.c, jsrc/m.h, jsrc/xenos/x15.c
They were just defined as aliases for define and free
=> Get rid of macros MALLOC and FREE

jsrc/array.hpp
This is the name of the second argument of the original macro SETIC, but
that argument has been removed from this method. This should make the
comment a little less confusing.
=> Remove targ from documentation of item_count in array.hpp

README.md
The way Ruby code uses anonymous lambdas is visually pretty different
from the listed code snippets. This might make the behaviour a bit more
clear for people mainly using Ruby. And personally, I think the syntax
is pretty neat.
=> Add Ruby example to code snippets

learning/J_EXAMPLES.md
Typo fix: `slidng` => `sliding`
=> Fix example of Pi calculation

jsrc/jeload.cpp
The meaning of it is described at
https://www.jsoftware.com/help/user/lib_sysenv.htm#FHS. I guess this has
once been a compile option, but is now set runtime in stdlib.ijs.
This also resulted in jdllver no longer being referenced, and a
possiblity to combine two string append statements.
=> Remove FHS from C source

jsrc/jconsole.c
It's just an alias to `dlsym`, use that directly.
=> Remove GETPROCADDRESS macro

jsrc/jeload.cpp
This is an application of "ES.21: Reduce scope": By moving the
definition inside the idef statement, compiling the code on platforms
other than MACH sill completely remove this unused variable.
The change works fine on my linux install, but it should be validated on a mac.
=> Move len variable in jeload.cpp

jsrc/adverbs/ar.c, jsrc/adverbs/as.c, jsrc/conjunctions/cr.c, jsrc/j.h, jsrc/ja.h, jsrc/m.c, jsrc/verbs/dyadic/take_drop.cpp, jsrc/verbs/v.c, jsrc/verbs/vcat.c, jsrc/verbs/vf.c, jsrc/verbs/vfrom.c, jsrc/verbs/vi.c, jsrc/verbs/vs.c, jsrc/words/w.c
resolves #184 
- replaced `virtual` & `virtualip` with direct calls
- removed unused `move` macro (`jtmove()` doesn't even exist anymore)
- removed couple unnecessary pointless indirection macros
=> Remove few macros

jsrc/array.hpp, jsrc/verbs/dyadic/take_drop.cpp
This replaces the pattern `(AT(x) & SPARSE) != 0` often seen in the
code. This hides the actual implementation from the call sites.
=> Add is_sparse function to array.hpp

CMakeLists.txt
This could:
1. allow compiling with gcc 10.2, accompishing the same as #164
2. allow for compiler upgrade to clang 11 / gcc 10
3. point 2 would enable c++17 features and #170 would compile
Tested with the following compiler versions on osx:
```
; /usr/local/Cellar/gcc/10.2.0_4/bin/gcc-10 --version
gcc-10 (Homebrew GCC 10.2.0_4) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
; clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
=> Enable use of newer compiler version

jsrc/algorithm.hpp, jsrc/verbs/dyadic/take_drop.cpp
I wanted to be able to test `constexpr` versions of the functions. So i'm including `<array>` for testing and added some range based overloads.
Added predicates:
`equal_to`
`not_equal_to`
`is_equal` - is_equal is a variadic version of `std::equal`
Added range overloads in `ranges` namespace.
`zip_find`
`zip_found`
`is_equal`
`is_mismatched` was removed as `!std::equal` covers it.
`auto` has to be on the right of the cv qualifiers. Or the clang-format new line won't trigger.
=> Add some more functions to algorithm.hpp

jlibrary/system/util/boot.ijs, jsrc/adverbs/ar.c, test/CMakeLists.txt, test/g18x.ijs
#4 
**g18x.ijs** seems to have had the same failure from the start of the port (same number of failing cases)
I didn't examine the failure further, just located it
**g420.ijs** failed to correctly locate foldr.ijs as explained in https://github.com/codereport/jsource/issues/4#issuecomment-768611946
~Again, if someone has better knowledge of j's path resolution & loading, the fix could be better...~
The loading of `fold` is now added to `boot.ijs`. The `fold` folder could maybe be relocated under some suitable `system` path.
=> Fix few disabled tests

README.md
We fixed this on An-Algorithm-Library. I think you copy and pasted from this. So this also had the underscore.
=> Remove underscore from Github link.

jsrc/array.hpp
The code was copied from a C macro, where ctype was an argument. There
is no need to wrap that in parentheses anymore. Also add some whitespace
to make it a bit more readable.
=> Small cleanup to make_array

CMakeLists.txt
https://cmake.org/cmake/help/latest/command/add_subdirectory.html
`If the EXCLUDE_FROM_ALL argument is provided then targets in the subdirectory will not be included in the ALL target of the parent directory by default, and will be excluded from IDE project files`
resolves: https://github.com/codereport/jsource/issues/199
Without `EXCLUDE_FROM_ALL`, anytime we add a target that compiles to An-Algorithm-Library it would compile them when you compile `ALL` in j.
=> Add EXCLUDE_FROM_ALL to add_subdirectory(An-Algorithm-Library)
