codereport/jsource

- hostdefs/hostdefs.c
- jsrc/andjnative.c
- jsrc/cpuinfo.c
- jsrc/d.c
- jsrc/f.c
- jsrc/io.c
- jsrc/j.h
- jsrc/jconsole.c
- jsrc/jeload.cpp
- jsrc/js.h
- jsrc/jversion-x.h
- jsrc/tsdll.c
- jsrc/vm.c
- jsrc/vz.c
- jsrc/x15.c
- jsrc/xd.c
- jsrc/xf.c
- jsrc/xh.c
- jsrc/xl.c
- jsrc/xsha.c
Cleaned Android conditional compilations, also replaced 0 with nullptr where found
Tests:
96% tests passed, 15 tests failed out of 406
Total Test time (real) = 275.12 sec
The following tests FAILED:
83 - g128x3 (SEGFAULT)
118 - g210a (SEGFAULT)
123 - g221 (Failed)
157 - g331 (SEGFAULT)
183 - g420stch (SEGFAULT)
226 - g5x30 (Failed)
234 - g602 (Failed)
257 - g9x40 (Failed)
272 - gebar (Failed)
303 - gmmf (Failed)
304 - gmmf1s (Failed)
305 - gmmf1u (Failed)
306 - gmmf1w (Failed)
397 - gu (Failed)
398 - gu0 (Failed)
> Cleaned Android conditional compilations  

- LIVESTREAM_LESSONS.md
https://www.appveyor.com/pricing/ free for 1 concurrent job unlimited public projects.
I saw you were having trouble with Travis-CI. I also had trouble with it. I went over to appveyor. I know you can use it to build on linux and windows. probably mac though I never tried.
Though I'd be interested in seeing you try other CI's to know how they work.
> Other CI suggestions for Lessons Learned 

- .clang-format
Note, we aren't about to format the whole code base, this is just the initial commit. I will modify it later.
> Adding initial clang-format config

- jsrc/CMakeLists.txt
- jsrc/adverbs/ap.c
- jsrc/adverbs/ar.c
- jsrc/adverbs/as.c
- jsrc/conjunctions/cip.c
- jsrc/js.h
- jsrc/verbs/va2.c
- jsrc/xt.c
Removes `SY_GETTOD`, `C_NA`, and `SY_ALIGN`
> Removing more SYS stuff

- test/tsu.ijs
In resposne to https://github.com/codereport/jsource/issues/4#issuecomment-768950690
> Decrease test flakiness

- .gitignore
> Add QtCreator config files to .gitignore

- .gitignore
> Added meson build files

- .gitignore
Hope this doesn't break anything
> Added some (random) files

- .clang-format
- docs/REFACTORINGS.md
- jsrc/CMakeLists.txt
- jsrc/j.h
- jsrc/jtype.h
- jsrc/verbs/monadic/tally.cpp
- jsrc/verbs/v.c
We also started tracking the refactorings we were doing in `REFACTORINGS.md`
> Porting TALLY (Part 1)

- CMakeLists.txt
- CONTRIBUTING.md
- docs/source/monadic.rst
- jsrc/CMakeLists.txt
- jsrc/adverbs/ai.c
- jsrc/adverbs/ao.c
- jsrc/adverbs/as.c
- jsrc/ja.h
- jsrc/je.h
- jsrc/t.c
- jsrc/verbs/monadic/tally.cpp
Resolves https://github.com/codereport/jsource/issues/91
> Rename `jttally` to `tally` & conditional documentation build

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codereport/jsource/99)
> README: adding Java example to Comparison of Languages

- README.md
I think the additional example is quite nice way to do the task in haskell, although the approach is a bit different compared to the others.
The website was the first I could find that would let you share the code with a link. It may nag about logging in when trying to run the snippet, but it is optional. If there is better alternative, the links could be changed.
> Add one more haskell example and runnable links

- docs/Doxyfile.in
Setting ``GENERATE_TREEVIEW = YES`` is all that is needed.
> generate treeview for docs

- jlibrary/system/util/p.ijs
Resolves https://github.com/codereport/jsource/issues/45
> `ut` for quickly running unit tests

- docs/source/conf.py
relative path works on my machine. I hope it's enough.
resolves: https://github.com/codereport/jsource/issues/158
> removed fixed path.

- jsrc/dtoa.c
- jsrc/dtoa.h
This file was full of preprocessor checks for harcoded values.
> Cleanup dtoa.c

- jsrc/format/f.c
- jsrc/j.c
- jsrc/jtype.h
- jsrc/k.c
- jsrc/m.c
- jsrc/verbs/vf.c
These had not much implemented, mainly formatting and conversions.
#111
> Remove extended complex & floating point

- CONTRIBUTING.md
- docs/CMakeLists.txt
- docs/source/conf.py
- Fixed cloning instructions for submodule
- Fixed breathe project path
- Added prerequisites for building documentation (resolves #127)
- Did I forget something? I did not test the requirements from clean slate
> Doc update and fixes

- CMakeLists.txt
- jsrc/CMakeLists.txt
- jsrc/verbs/dyadic/take_drop.cpp
Necessary followup changes from https://github.com/codereport/An-Algorithm-Library/pull/1
> Update CMake for `aal`

- README.md
- jsrc/array.hpp
- jsrc/verbs/dyadic/take_drop.cpp
- learning/LIVESTREAM_LESSONS.md
- learning/REFACTORINGS.md
Closes https://github.com/codereport/jsource/issues/196.
> Adding `aal::var::transform` + cleanup + docs/README
